name: Deploy on VPS
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/dev/quentin-aslan
            git pull origin main
            rm .env
            touch .env
            echo NITRO_PORT=${{ secrets.NITRO_PORT }} >> .env
            echo NUXT_STRAPI_READ_ONLY=${{ secrets.NUXT_STRAPI_READ_ONLY }} >> .env
            echo NUXT_STRAPI_BASE_URL=${{ secrets.NUXT_STRAPI_BASE_URL }} >> .env
            npm ci
            npm run build
            sudo systemctl restart quentin-aslan
